### ISSUE TITLE
Resolve all issues with DNS issues and document our guidance

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#10]
We need to handle the fact that keeping a HttpClientHandler alive forever results in stale DNS.

Today our strategy is to rotate the handlers periodically.

**Comment by mkArtakMSFT** [comment]
@rynowak is this required for preview1? /cc: @glennc

**Comment by rynowak** [comment]
No, this should be moved.

**Comment by mkArtakMSFT** [comment]
@rynowak thanks!

**Comment by karelz** [comment]
I would be interested in repro / debugging done on the case. It is suspicious that DNS is not refreshed after handler disposal. How certain are you that's the case?

**Comment by rynowak** [comment]
The apps that I used to test this are here: https://github.com/rynowak/HttpClientFactoryDemos/tree/master/Dns and a description of my process/findings is herehttps://github.com/aspnet/HttpClientFactory/wiki/Exploring-DNS-issues

I'm going to try testing this on 2.0 as well. Unfortunately my environment for testing this is my LAN at home.

**Comment by karelz** [comment]
@Priya91 looked at CurlHandler - it seems we are just calling into libcurl to resolve DNS, etc. It might be limitation/bug in libcurl. @Priya91 what would be the best way to confirm?

@rynowak nit: can you please fix your link?

**Comment by Priya91** [comment]
> @Priya91 what would be the best way to confirm?

I've looked at the libcurl source code, it looks like libcurl maintains it's own dns cache, and reuses the dns results from its custom cache. Curl does expose an option to control the timeout for clearing out this cache, [```CURLOPT_DNS_CACHE_TIMEOUT```](https://curl.haxx.se/libcurl/c/CURLOPT_DNS_CACHE_TIMEOUT.html). The default timeout is 60 seconds, this option can be set to 0 to disable caching. They also mention this custom libcurl cache doesn't honour the TTL property on the Dns entries, this cache timeout is entirely speculative that a name will resolve to the same address for a certain small amount of time into the future.

Also note that in .NET Core, we extend this dns cache timeout to 10 minutes, to mimic the behavior on Windows [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.EasyRequest.cs#L315). But note that this option is per EasyRequest, and a new EasyRequest is created for each ```HttpClient.SendAsync```.

**Comment by rynowak** [comment]
Thanks for the details @Priya91. I'll give that a try.

I wasn't able to find anything else on my machine that was seeing stale DNS. It was just HttpClient. Chrome successfully update, as did `dscacheutil`.

It sounds like it would also useful to just run the curl CLI tool in a loop at the same time. If we're seeing a difference in behavior for a new HttpClient vs a call to `curl http://...` that should tell us something right?

**Comment by rynowak** [comment]
Yeah, I'm not concerned about a timeout of 90 seconds vs 2 minutes... I left it running for a *loooong* time without seeing any changes.

**Comment by rynowak** [comment]
@karelz @Priya91 - I can confirm that calling curl in a loop reacts to DNS updates quite quickly.
```
while true
do
  curl "http://test.example.lan:5000"
  echo ""
  pause 3
done
```

I've trimmed down my repro to just use HttpClient (no more HttpClientFactory). I can reproduce the lack of DNS updates on both netcoreapp2.1 and netcoreapp2.0. I've let each of these run for 10+ minutes just in case. 

`curl` from the command line reliably sees the DNS updates almost instantly.

**Comment by karelz** [comment]
@rynowak doesn't your `curl` sample spin off a new process in each iteration?
The question is what happens in a C/C++ app which calls into libcurl in a loop (after setting the timeout to the 10 mins as .NET Core does). If that works, we have a bug in .NET Core.

**Comment by rynowak** [comment]
This program responds to a DNS update almost instantly:
```
#include <stdio.h>
#include <unistd.h>
#include <curl/curl.h>

int main(int argc, const char * argv[]) {

    curl_global_init(CURL_GLOBAL_ALL);
    
    while (1)
    {
        CURL *curl = curl_easy_init();
        curl_easy_setopt(curl, CURLOPT_URL, "http://test.example.lan:5000/");
        curl_easy_setopt(curl, CURLOPT_DNS_CACHE_TIMEOUT, 10 * 60);
        
        CURLcode result = curl_easy_perform(curl);
        if (result != CURLE_OK)
        {
            printf("Error %s\n", curl_easy_strerror(result));
            curl_easy_cleanup(curl);
            break;
        }
        
        curl_easy_cleanup(curl);
        printf("\n");
        
        sleep(3);
    }
    
    curl_global_cleanup();
    return 0;
}
```

**Comment by Priya91** [comment]
@rynowak You've used easy request, which is synchronous, the ideal repro would be with a multi handle. We don't have a local dns setup to test this, so can you please try a repro with multi handle

**Comment by davidfowl** [comment]
Aren’t we using the easy request in corefx?

**Comment by Priya91** [comment]
Corefx creates easy requests for each SendAsync and registers them with the multi handle, there's a unique multi handle for each handler object. The multi handler executes the easy requests.

**Comment by rynowak** [comment]
@Priya91 - if you can provide me with a code sample that would give you some more conclusive answers then I'd be happy to run it. Right now this feels a bit like I'm playing a guessing game 😆

**Comment by Priya91** [comment]
@rynowak I have a couple of tests to root cause this,

1. Modify the ```const int DnsCacheTimeoutSeconds = 0``` [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.EasyRequest.cs#L317) to disable caching, and verify if libcurl caching is the problem here.

2. Try this native app on the same machine, as many iterations to observe the dns change, with appropriate infinite loop, without sleep as you are not sleeping the dotnet process between sending subsequent requests,

```c++
#include <stdio.h>
#include <string.h>
#include <curl/curl.h>

#define HANDLECOUNT 200

int main(void)
{
  CURL *handles[HANDLECOUNT];
  CURLM *multi_handle;

  int still_running; 
  int i;

  CURLMsg *msg; 
  int msgs_left; 
  FILE *filep = fopen("output.txt", "wb");
  multi_handle = curl_multi_init();
  while (true)
  {
    for(i=0; i<HANDLECOUNT; i++)
    {
      handles[i] = curl_easy_init();
      curl_easy_setopt(handles[i], CURLOPT_URL, "your-url");
      curl_easy_setopt(handles[i], CURLOPT_DNS_CACHE_TIMEOUT, 10 * 60);
      // Get diagnostic data
      // curl_easy_setopt(handles[i], CURLOPT_VERBOSE, 1L);
      // curl_easy_setopt(handles[i], CURLOPT_STDERR, filep);
     
     // Add the easy request to the multi handle.
     curl_multi_add_handle(multi_handle, handles[i]);
    }
 
    do
    {
      curl_multi_perform(multi_handle, &still_running);
    } while (still_running != 0);

    while((msg = curl_multi_info_read(multi_handle, &msgs_left)))
    {
      if(msg->msg == CURLMSG_DONE)
      {
        printf("HTTP transfer completed with status %d\n", msg->data.result);
      }
    }
    for(i=0; i<HANDLECOUNT; i++)
      curl_easy_cleanup(handles[i]);
  }
  curl_multi_cleanup(multi_handle);
  return 0;
}
```

**Comment by Priya91** [comment]
You can download the OSX version of the System.Net.Http.dll with zero cache timeout here: https://github.com/Priya91/FileShare/blob/master/System.Net.Http.dll

**Comment by rynowak** [comment]
@Priya91 - great, I will give this a try. Thanks!

**Comment by rynowak** [comment]
Hi @Priya91 @karelz - the private build of System.Net.Http.dll still demonstrates the problem. I ended up simplifying the repro down to the following (at the bottom) and and letting it run for 12+ minutes. After making the DNS change the correct output can be seen immediately using curl at the command line, so the correct information is available.

I would suggest at this point that your team set up an environment where you can test and debug this. Linux is the primary use case for this and will probably be an easier path to set something up since you can use docker or VMs or Azure.

**Comment by Priya91** [comment]
@rynowak Thanks for the investigation. 

@wfurt Can you help setup an environment with DNS server to test this? 
cc @karelz

**Comment by Priya91** [comment]
@rynowak I'm experiencing some issues with the setup, can you send an email on corpnet, so that I can quickly address my issues?

**Comment by rynowak** [comment]
To close the trail of breadcrumbs here, I was able to resolve my problem with OSX. https://github.com/dotnet/corefx/issues/26651#issuecomment-366482574

HttpClient won't refresh DNS when using libcurl + LibreSSL which is not supported. Switching to OpenSSL solves the issue.

**Comment by rynowak** [comment]
Authoring of the docs is going on right now. I'll close this issue once we've put all of the info in the docs.

**Comment by rynowak** [comment]
Closing this out because I've handed off all of the relevant info to @stevejgordon who is helping us out with the docs 👍 No more action from the engineering team is planned or required here.

**Comment by stijnherreman** [comment]
@rynowak Where can I find this documentation? Are the DNS issues resolved in HttpClientFactory only, or are they resolved in HttpClient?

**Comment by karelz** [comment]
@stijnherreman HttpClient does not use libcurl anymore by default, so you should be good, unless you have reasons to switch off `SocketsHttpHandler`.

**Comment by rynowak** [comment]
Hi @stijnherreman - I did an initial writeup here: https://github.com/aspnet/HttpClientFactory/wiki/Exploring-DNS-issues 

It's out of date because this was done before the socket handler was introduced. I'm told that the SocketsHttpHandler (default in .NET Core 2.1) solves these issues.

**Comment by stijnherreman** [comment]
Thank you both for the clarification. It seems to be a confusing topic, various blog posts and even [the official documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1) say that the DNS issues are resolved by `HttpClientFactory`:

> An `IHttpClientFactory` can be registered and used to configure and create HttpClient instances in an app. It offers the following benefits:
> 
> * ...
> * Manages the pooling and lifetime of underlying `HttpClientMessageHandler` instances to avoid common DNS problems that occur when manually managing `HttpClient` lifetimes.

**Comment by karelz** [comment]
@stijnherreman which part is confusing? I find the DNS sentence you quoted from the article correct. It doesn't say that `HttpClientHandler` in .NET Core 2.1 is not fixed.
Note that `HttpClientFactory` works on all platforms, not just the one which is fixed (.NET Core 2.1).

**Comment by stijnherreman** [comment]
Am I not reading it right? To me, it says that manually managing `HttpClient` instances can still give you DNS problems, you need to use `HttpClientFactory` to avoid the DNS problems.

Further, there's this part of the .NET Core 2.1 release notes:

> We built a new from-the-ground-up HttpClientHandler called SocketsHttpHandler to improve networking performance. It’s a C# implementation of HttpClient based on .NET sockets and Span<T>.
> 
> SocketsHttpHandler is now the default implementation for HttpClient. The biggest win of SocketsHttpHandler is performance. It is a lot faster than the existing implementation. It also eliminates platform-specific dependencies and enables consistent behavior across operating systems.

It only talks about performance, it doesn't say anything about changes to avoid DNS problems.

**Comment by karelz** [comment]
@stijnherreman manually managing `HttpClient` instances can lead to DNS problems, unless you use `SocketsHttpHandler.PooledConnectionLifetime` like `HttpClientFactory` does. Does it make sense?
