### ISSUE TITLE
Asp.net restart: Cannot find method

### ISSUE THREAD

**Issue by pengweiqhca** [aspnet/HttpClientFactory#174]
Cannot find method:“Microsoft.Extensions.DependencyInjection.IHttpClientBuilder Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.ConfigureHttpClient(Microsoft.Extensions.DependencyInjection.IHttpClientBuilder, System.Action`1<System.Net.Http.HttpClient>)”

**Comment by rynowak** [comment]
If you see an error like this then it's because you have a mismatch of binaries that you're using at compile time and runtime. This is not a product bug. 

Can you provide more information?

**Comment by pengweiqhca** [comment]
first time: access ok
rebuild project: access error
restart w3wp: access ok

**Comment by pengweiqhca** [comment]
@rynowak My demo https://github.com/pengweiqhca/IisCrash
open solution, then CTRL+F5, access ok. If rebuild project, iisexpress creash

**Comment by martincostello** [comment]
You repro shows that you're still using [RC1 of ASP.NET Core 2.1](https://github.com/pengweiqhca/IisCrash/blob/b4418d0e0badc8db9a99aab1c6bd64b1e5eee635/IisCrash.csproj#L67). You should update it to the released version in case it's just a bug that was fixed before release.

**Comment by pengweiqhca** [comment]
I upgrade Microsoft.Extensions.Http to 2.2.0-preview2, but the iis still crash.
If you delete web.config runtime section, it ok

**Comment by rynowak** [comment]
I can't reproduce this. There's also no code here that references HttpClient factory so I'm not sure how that would be possible to begin with.

**Comment by rynowak** [comment]
Closing due to lack of response
